DATA:
    DATASET: 'Potsdam'
    BATCH_SIZE: 8
    BATCH_SIZE_VAL: 4
    DATA_PATH: '/data/sdu02_peach/potsdam_processing_tif_448'
    CROP_SIZE: (448, 448)
    NUM_CLASSES: 6
TRAIN:
    BASE_LR: 0.01
    END_LR: 0.0
    ITERS: 160000
    IGNORE_INDEX: 255
    LOSS: "MixSoftmaxCrossEntropyLoss"
    LR_SCHEDULER:
        NAME: 'PolynomialDecay'
    OPTIMIZER:
        WEIGHT_DECAY: 1e-4
        GRAD_CLIP: 1.0
        NAME: 'SGD'
        MOMENTUM: 0.9
MODEL:
    NAME: "EMRT"
    ENCODER:
        TYPE: "resnet50"
#        TYPE: "resnet101"
        MULTI_GRID:
        MULTI_DILATION:

    OUTPUT_STRIDE: 32 #resnet output stride
    DEFORMABLE:
        EMBED_DIM: 256
        DEPTH: 4
        NUM_HEADS: 8
        MLP_RATIO: 3.
        HID_DIM: 64
    AUX:
        AUXIHEAD: False
        AUXHEAD_ALIGN_CORNERS: False
SAVE_DIR: "/data/sdu02_peach/Paddle/EMRT_448x448_160k_potsdam_pretrain_resnet50_os32"
VAL:
    MULTI_SCALES_VAL: False
    IMAGE_BASE_SIZE: 448
    CROP_SIZE: [448, 448]
SAVE_FREQ_CHECKPOINT: 2000