DATA:
    DATASET: 'Potsdam'
    BATCH_SIZE: 8
    BATCH_SIZE_VAL: 4
    DATA_PATH: '/data/sdu02_peach/potsdam_processing_tif'
    CROP_SIZE: (256, 256)
    NUM_CLASSES: 6
TRAIN:
    BASE_LR: 0.01
    END_LR: 0.0
    ITERS: 160000
    IGNORE_INDEX: 255
    LOSS: "MixSoftmaxCrossEntropyLoss"  #   "MixSoftmaxCrossEntropyLoss"  #CrossEntropyLoss
    LR_SCHEDULER:
        NAME: 'PolynomialDecay'
    OPTIMIZER:
        WEIGHT_DECAY: 1e-4
        GRAD_CLIP: 1.0
        NAME: 'SGD'
        MOMENTUM: 0.9
MODEL:
    NAME: "EMRT_Segformer"
    ENCODER:
        TYPE: "segformer_b4"
        MULTI_GRID:
        MULTI_DILATION:

    OUTPUT_STRIDE: 32 #32 #resnet output stride
    DEFORMABLE:
        EMBED_DIM: 256
        DEPTH: 4
        NUM_HEADS: 8
        MLP_RATIO: 3.
        HID_DIM: 64
    AUX:
        AUXIHEAD: False
        AUXHEAD_ALIGN_CORNERS: False
    PRETRAINED: '/data/sdu02_peach/Paddle_pdparams/pretrain_models_paddleSeg/mix_vision_transformer_b4.pdparams'

SAVE_DIR: "/data/sdu02_peach/Paddle/EMRT_256x256_160k_potsdam_segformerb4_pretrain"

VAL:
    MULTI_SCALES_VAL: False
    IMAGE_BASE_SIZE: 256
    CROP_SIZE: [256, 256]
SAVE_FREQ_CHECKPOINT: 2000