DATA:
    DATASET: 'Potsdam'
    BATCH_SIZE: 8
    BATCH_SIZE_VAL: 4
    DATA_PATH: '/data/sdu02_peach/potsdam_processing_tif'
    CROP_SIZE: (256, 256)
    NUM_CLASSES: 6
TRAIN:
    BASE_LR: 0.01
    END_LR: 0.0
    ITERS: 160000
    IGNORE_INDEX: 255
    LOSS: "MixSoftmaxCrossEntropyLoss"  #   "MixSoftmaxCrossEntropyLoss"  #CrossEntropyLoss
    LR_SCHEDULER:
        NAME: 'PolynomialDecay'
    OPTIMIZER:
        WEIGHT_DECAY: 1e-4
        GRAD_CLIP: 1.0
        NAME: 'SGD'
        MOMENTUM: 0.9
MODEL:
    NAME: "EMRT_ViT"
    ENCODER:
        TYPE: 'ViT'
        OUT_INDICES: [9, 14, 19, 23]
    PRETRAINED: '/data/sdu02_peach/Paddle_pdparams/pretrain_models_paddleViT_Segmentation/vit_large_patch16_224.pdparams'
    TRANS:
        PATCH_SIZE: 16
        HIDDEN_SIZE: 1024 # 768(Base), 1024(Large), 1280(Huge)
        MLP_RATIO: 4     # same as mlp_ratio = 4.0
        NUM_HEADS: 16    # 12(Base), 16(Large), 16(Huge)
        NUM_LAYERS: 24   # 12(Base), 24(Large), 32(Huge)
        QKV_BIAS: True
    DEFORMABLE:
        EMBED_DIM: 256
        DEPTH: 4
        NUM_HEADS: 8
        MLP_RATIO: 3.
        HID_DIM: 64
    AUX:
        AUXIHEAD: True
        AUXHEAD_ALIGN_CORNERS: False
    AUXFCN:
        IN_CHANNELS: 1024
        UP_RATIO: 2
SAVE_DIR: "/data/sdu02_peach/Paddle/EMRT_256x256_160k_potsdam_vit_pretrain"
VAL:
    MULTI_SCALES_VAL: False
    IMAGE_BASE_SIZE: 256
    CROP_SIZE: [256, 256]
SAVE_FREQ_CHECKPOINT: 2000