DATA:
    BATCH_SIZE: 8  # per GPU [total bs is set to 8 or 16]
    BATCH_SIZE_VAL: 4  # per GPU
    DATASET: 'LoveDA' # dataset name
    DATA_PATH: '/data/sdu02_peach/2021LoveDA_merge_256'
    CROP_SIZE: (256,256)
    NUM_CLASSES: 7
MODEL:
    NAME: 'SETR_PUP'
    ENCODER:
        TYPE: 'ViT'
        OUT_INDICES: [9, 14, 19, 23]   
    PRETRAINED: '/data/sdu02_peach/pretrain_models/vit_large_patch16_224.pdparams'
    DECODER_TYPE: 'PUP_VisionTransformerUpHead'
    PUP:
       INPUT_CHANNEL: 1024
       NUM_CONV: 4
       NUM_UPSAMPLE_LAYER: 4
       CONV3x3_CONV1x1: True
       ALIGN_CORNERS: False
    TRANS:
        PATCH_SIZE: 16
        HIDDEN_SIZE: 1024 # 768(Base), 1024(Large), 1280(Huge)
        MLP_RATIO: 4     # same as mlp_ratio = 4.0
        NUM_HEADS: 16    # 12(Base), 16(Large), 16(Huge)
        NUM_LAYERS: 24   # 12(Base), 24(Large), 32(Huge)
        QKV_BIAS: True
    AUXPUP:
       INPUT_CHANNEL: 1024
       NUM_CONV: 2
       NUM_UPSAMPLE_LAYER: 2
       CONV3x3_CONV1x1: True
       ALIGN_CORNERS: False
    AUX:
       AUXIHEAD: True
TRAIN:
    BASE_LR: 0.01
    END_LR: 0.0
    DECODER_LR_COEF: 10.0
    ITERS: 40000
    POWER: 0.9
    DECAY_STEPS: 40000
    LR_SCHEDULER:
        NAME: 'PolynomialDecay'
    OPTIMIZER:
        GRAD_CLIP: 1.0
        WEIGHT_DECAY: 1e-4
        NAME: 'SGD'
        MOMENTUM: 0.9
VAL:
    MULTI_SCALES_VAL: False
    SCALE_RATIOS: [0.5, 0.75, 1.0, 1.25]
    IMAGE_BASE_SIZE: 256
    CROP_SIZE: [256,256]
    STRIDE_SIZE: [256,256]
SAVE_DIR: "/data/sdu02_peach/Paddle/SETR_PUP_Large_256x256_160k_loveda_bs_8_max10"
SAVE_FREQ_CHECKPOINT: 4000 #100次验证一下 ,默认是2000

        

