DATA:
    BATCH_SIZE: 1  # per GPU [total bs is set to 8 or 16]
    BATCH_SIZE_VAL: 2  # per GPU
    DATASET: 'Vaihingen' # dataset name
    DATA_PATH: '/data/sdu02_peach/Vaihingen_processing_tif_512'
    CROP_SIZE: (512,512)  # input_size (training)
    NUM_CLASSES: 6
MODEL:
    NAME: 'DPT'
    ENCODER:
        TYPE: 'ViT'
        OUT_INDICES: [5, 11, 17, 23] 
    PRETRAINED: '/data/sdu02_peach/pretrain_models/vit_large_patch16_224.pdparams'  #default: None
    DECODER_TYPE: 'DPTHead'
    DPT:
        HIDDEN_FEATURES: [256, 512, 1024, 1024]
        FEATURES: 256
        READOUT_PROCESS: 'project'
    NUM_CLASSES: 6
    TRANS:
        PATCH_SIZE: 16
        HIDDEN_SIZE: 1024 # 768(Base), 1024(Large), 1280(Huge)
        MLP_RATIO: 4     # same as mlp_ratio = 4.0
        NUM_HEADS: 16    # 12(Base), 16(Large), 16(Huge)
        NUM_LAYERS: 24   # 12(Base), 24(Large), 32(Huge)
        QKV_BIAS: True
        KEEP_CLS_TOKEN: True
TRAIN:
    BASE_LR: 0.005
    END_LR: 0.0
    DECODER_LR_COEF: 10.0
    ITERS: 120000
    POWER: 0.9
    DECAY_STEPS: 120000
    LR_SCHEDULER:
        NAME: 'PolynomialDecay'
    OPTIMIZER:
        GRAD_CLIP: 1.0
        WEIGHT_DECAY: 1e-4
        NAME: 'SGD'
        MOMENTUM: 0.9
VAL:
    MULTI_SCALES_VAL: False
    SCALE_RATIOS: [0.5, 0.75, 1.0]
    IMAGE_BASE_SIZE: 512
    CROP_SIZE: [512,512]
    STRIDE_SIZE: [341,341]
    MEAN: [127.5, 127.5, 127.5]
    STD: [127.5, 127.5, 127.5]
SAVE_DIR: "/data/sdu02_peach/Paddle/DPT_Large_512x512_120k_vaihingen_bs_8"
SAVE_FREQ_CHECKPOINT: 1000
        

