DATA:
    DATASET: 'Potsdam'
    BATCH_SIZE: 8
    BATCH_SIZE_VAL: 4
    DATA_PATH: '/data/sdu02_peach/potsdam_processing_tif'
    CROP_SIZE: (256, 256)
    NUM_CLASSES: 6
TRAIN:
    BASE_LR: 0.01
    END_LR: 0.0
    ITERS: 160000
    IGNORE_INDEX: 255
    LOSS: "MixSoftmaxCrossEntropyLoss"
    LR_SCHEDULER:
        NAME: 'PolynomialDecay'
    OPTIMIZER:
        WEIGHT_DECAY: 1e-4
        GRAD_CLIP: 1.0
        NAME: 'SGD'
        MOMENTUM: 0.9
MODEL:
    NAME: "Trans2Seg"
    ENCODER:
        TYPE: "resnet50c"
        MULTI_GRID:
        MULTI_DILATION:
    TRANS2SEG:
        EMBED_DIM: 256
        DEPTH: 4
        NUM_HEADS: 8
        MLP_RATIO: 3.
        HID_DIM: 64
    AUX:
        AUXIHEAD: False
        AUXHEAD_ALIGN_CORNERS: False
    PRETRAINED: "/data/sdu02_peach/pretrain_models/resnet50c.pdparams"
VAL:
    MULTI_SCALES_VAL: False
    IMAGE_BASE_SIZE: 256
    CROP_SIZE: [256, 256]
SAVE_DIR: "/data/sdu02_peach/Paddle/Trans2Seg_medium_256x256_160k_potsdam_pretrain"
SAVE_FREQ_CHECKPOINT: 2000